# -*- coding: utf-8 -*-
"""FIN 553 Project 3 Staubus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXIYLntINQJZGP9v5AQS3YtMhETXjFQy
"""

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import pandas as pd

rng = jax.random.PRNGKey(0)

γ = 2.
β = 0.95
T = 300
x0 = 10.
Rf = 1.04

batch_size = 64

def u(c):
  return c**(1 - γ) / (1 - γ)

def c(theta, x):
  return jax.nn.sigmoid(theta) * x


def stock_return(rng):
  μs = 0.06
  σs = 0.2
  ε = jax.random.normal(rng, ())
  log_return = μs + σs * ε
  return jnp.exp(log_return)


def L(params, rng, batch_size):
  theta_consumption, theta_investment = params
  def one_simulation(rng):
    rng_t = jax.random.split(rng, T)
    x = x0
    V = 0.

    carry = x, V
    inputs = jnp.arange(300), rng_t

    def core(carry, inputs):
      x, V = carry
      t, rng = inputs
      ct = c(theta_consumption[t], x)
      α = jax.nn.sigmoid(theta_investment[t])
      cx = ct / x
      ut = u(ct)

      V = V + ut * β**t
      R = stock_return(rng)
      st = (x - ct)
      x = st * (R * α + (1 - α) * Rf)

      return (x, V), cx

    (x, V), ct = jax.lax.scan(core, carry, inputs)
    return V, ct

  rng_s = jax.random.split(rng, batch_size)
  V, ct = jax.vmap(one_simulation)(rng_s)
  return V.mean(), ct.mean(0)


import optax
optimizer = optax.adam(-1e-2)

def sigmoid_inverse(x):
  return jnp.log(x / (1 - x))

@jax.jit
def update(params, opt_state, rng):
  rng = jax.random.split(rng)[0]
  grad, _ = jax.grad(L, has_aux=True)(params, rng, batch_size)
  updates, opt_state = optimizer.update(grad, opt_state)
  params = optax.apply_updates(updates, params)
  return params, opt_state, rng

theta_consumption = sigmoid_inverse(0.01) * jnp.ones(300)
theta_investment = jnp.zeros(300)
params = (theta_consumption, theta_investment)
opt_state = optimizer.init(params)

for i in range(5000):
  params, opt_state, rng = update(params, opt_state, rng)

theta_consumption, theta_investment = params

df = pd.DataFrame({
    'consumption ratio': jax.nn.sigmoid(theta_consumption),
    'investment ratio': jax.nn.sigmoid(theta_investment)
})

display(df.head())

df.to_csv('results.csv', header=False)